server:
  port: 8086

spring:
  application:
    name: monitoring

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
