server:
  port: 8080

spring:
  application:
    name: apigateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
        - id: traffic-routing
          uri: lb://trafficrouting
          predicates:
            - Path=/route/**
        - id: ml-service
          uri: lb://mlservice
          predicates:
            - Path=/ml/**
