apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicediscovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicediscovery
  template:
    metadata:
      labels:
        app: servicediscovery
    spec:
      containers:
      - name: servicediscovery
        image: servicediscovery:latest
        ports:
        - containerPort: 8761 