groups:
- name: ark-ai-lb-alerts
  rules:
  - alert: HighLatency
    expr: routing_latency > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High routing latency detected
      
  - alert: HighCPUUsage
    expr: cpu_usage > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High CPU usage detected
      
  - alert: ServiceFailure
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Service is down 