server:
  port: 8082

spring:
  application:
    name: trafficrouting

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Add any additional configuration for AI-based routing here
