server:
  port: 8083

spring:
  application:
    name: ratelimiter

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
