apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: trafficrouting-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trafficrouting
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: External
    external:
      metric:
        name: ai-predicted-traffic-spike
      target:
        type: Value
        value: 1 