apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficrouting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficrouting
  template:
    metadata:
      labels:
        app: trafficrouting
    spec:
      containers:
      - name: trafficrouting
        image: trafficrouting:latest
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10 