apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficrouting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficrouting
  template:
    metadata:
      labels:
        app: trafficrouting
    spec:
      containers:
      - name: trafficrouting
        image: trafficrouting:latest
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      networkPolicies:
      - podSelector:
          matchLabels:
            app: trafficrouting
        policyTypes:
        - Ingress
        - Egress
      podDisruptionBudget:
        maxUnavailable: 1
      serviceMeshIntegration:
        enabled: true
      healthChecks:
        - name: trafficrouting-health
          path: /actuator/health
          port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10 