server:
  port: 8085

spring:
  application:
    name: mlservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always

ml:
  model-path: /opt/models/latest-model.pkl
